apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: deploy-frontend-
  namespace: argo
spec:
  # Use the WorkflowTemplate that contains the reusable pipeline
  workflowTemplateRef:
    name: deploy-frontend-pipeline
  entrypoint: deploy-frontend-pipeline
  arguments:
    parameters:
    - name: repo-url
      value: "https://github.com/BenHesketh21/hello-world-gitops.git" # <--- update with real repo URL
    - name: base-branch
      value: "main"
    - name: output-branch
      value: "promotions"
    - name: chart-path
      value: "chart" # path inside the repo to the Helm chart
    - name: values-file
      value: "charts/values/frontend/dev.yaml" # path inside repo to values file (adjust as needed)
    - name: release-name
      value: "frontend"
    - name: app-name
      value: "hello-world-frontend"