apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-helm-pipeline
  namespace: argo
spec:
  arguments:
    parameters:
    - name: repo-url
      value: ""
    - name: base-branch
      value: main
    - name: output-branch
      value: promotions
    - name: chart-path
      value: chart
    - name: values-file
      value: values.yaml
    - name: release-name
      value: api
    - name: app-name
      value: api
    - name: commit-message
      value: "Promote API via Argo Workflows"
  volumeClaimTemplates:
    - metadata:
        name: work
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 64Mi
  templates:
  - name: deploy-helm-pipeline
    dag:
      tasks:
      - name: clone-dry
        templateRef:
          name: git-common
          template: clone
        arguments:
          parameters:
          - name: repo
            value: "{{workflow.parameters.repo-url}}"
          - name: branch
            value: "{{workflow.parameters.base-branch}}"
          - name: dir
            value: "/work/dry"
      - name: clone-output
        templateRef:
          name: git-common
          template: clone
        arguments:
          parameters:
          - name: repo
            value: "{{workflow.parameters.repo-url}}"
          - name: branch
            value: "{{workflow.parameters.output-branch}}"
          - name: dir
            value: "/work/output"
      - name: clear
        templateRef:
          name: git-common
          template: clear
        arguments:
          parameters:
          - name: path
            value: "/work/output/"
        dependencies: ["clone-output"]
      - name: render-helm
        templateRef:
          name: gitops-common-templates
          template: helm-template-to-file
        arguments:
          parameters:
          - name: chart-path
            value: "/work/dry/{{workflow.parameters.chart-path}}"
          - name: values-file
            value: "/work/dry/{{workflow.parameters.values-file}}"
          - name: output
            value: "/work/dry/output"
          - name: release-name
            value: "{{workflow.parameters.release-name}}"
        dependencies: ["clone-dry"]
      - name: copy
        templateRef:
          name: git-common
          template: copy
        arguments:
          parameters:
          - name: from
            value: /work/dry/output
          - name: to
            value: /work/output/
        dependencies: [render-helm, clear]
      - name: commit-and-push
        templateRef:
          name: gitops-common-templates
          template: git-commit-push
        arguments:
          parameters:
          - name: repo-path
            value: "/work/output"
          - name: branch
            value: "{{workflow.parameters.output-branch}}"
          - name: commit-message
            value: "{{workflow.parameters.commit-message}}"
        dependencies: ["copy"]
    #   - name: argocd-sync
    #     templateRef:
    #       name: gitops-common-templates
    #       template: argocd-sync-wait
    #     arguments:
    #       parameters:
    #       - name: app-name
    #         value: "{{workflow.parameters.app-name}}"
    #       - name: timeout
    #         value: "300"

  volumes:
  - name: git-ssh
    secret:
      secretName: github-ssh-key
      defaultMode: 0600
