apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-helm-pipeline
  namespace: argo
spec:
  templates:
  - name: deploy-helm-pipeline
    inputs:
      parameters:
      - name: repo-url
      - name: base-branch
      - name: output-branch
      - name: chart-path
      - name: values-file
      - name: release-name
      - name: app-name
      - name: commit-message
        value: "Deploy {{inputs.parameters.app-name}} via Argo Workflow" # default commit message, can be overridden
      - name: workspace
    dag:
      tasks:
      - name: clone-dry
        templateRef:
          name: git-common
          template: clone
        arguments:
          parameters:
          - name: repo
            value: "{{inputs.parameters.repo-url}}"
          - name: branch
            value: "{{inputs.parameters.base-branch}}"
          - name: dir
            value: "/work/dry"
          - name: workspace
            value: "{{inputs.parameters.workspace}}"
      - name: clone-output
        templateRef:
          name: git-common
          template: clone
        arguments:
          parameters:
          - name: repo
            value: "{{inputs.parameters.repo-url}}"
          - name: branch
            value: "{{inputs.parameters.output-branch}}"
          - name: dir
            value: "/work/output"
          - name: workspace
            value: "{{inputs.parameters.workspace}}"
      - name: clear
        templateRef:
          name: git-common
          template: clear
        arguments:
          parameters:
          - name: path
            value: "/work/output/"
          - name: workspace
            value: "{{inputs.parameters.workspace}}"
        dependencies: ["clone-output"]
      - name: render-helm
        templateRef:
          name: gitops-common-templates
          template: helm-template-to-file
        arguments:
          parameters:
          - name: chart-path
            value: "/work/dry/{{inputs.parameters.chart-path}}"
          - name: values-file
            value: "/work/dry/{{inputs.parameters.values-file}}"
          - name: output
            value: "/work/dry/output"
          - name: release-name
            value: "{{inputs.parameters.release-name}}"
          - name: workspace
            value: "{{inputs.parameters.workspace}}"
        dependencies: ["clone-dry"]
      - name: copy
        templateRef:
          name: git-common
          template: copy
        arguments:
          parameters:
          - name: from
            value: /work/dry/output
          - name: to
            value: /work/output/
          - name: workspace
            value: "{{inputs.parameters.workspace}}"
        dependencies: [render-helm, clear]
      - name: commit-and-push
        templateRef:
          name: gitops-common-templates
          template: git-commit-push
        arguments:
          parameters:
          - name: repo-path
            value: "/work/output"
          - name: branch
            value: "{{inputs.parameters.output-branch}}"
          - name: commit-message
            value: "{{inputs.parameters.commit-message}}"
          - name: workspace
            value: "{{inputs.parameters.workspace}}"
        dependencies: ["copy"]
      - name: argocd-sync
        templateRef:
          name: gitops-common-templates
          template: argocd-sync-wait
        arguments:
          parameters:
          - name: app-name
            value: "{{inputs.parameters.app-name}}"
          - name: timeout
            value: "300"
        dependencies: ["commit-and-push"]
  - name: approve-promotion
    suspend: {}

  volumes:
  - name: git-ssh
    secret:
      secretName: github-ssh-key
      defaultMode: 0600
