environment: dev
serviceName: hello-world-frontend

image:
  registry: ghcr.io/benhesketh21
  repository: gitops-hello-world-frontend
  tag: "0.0.1"

ingress:
  enabled: true
  hosts: 
  - host: hello-world.local
    paths:
    - path: /
      pathType: Prefix

env:
  API_URL: http://hello-world-api-dev:8080