environment: dev
serviceName: hello-world-frontend

image:
  registry: ghcr.io/benhesketh21
  repository: gitops-hello-world-frontend
  tag: "latest"

ingress:
  enabled: true
  hosts: 
  - host: hello-world.local
    paths:
    - path: /
      pathType: Prefix