environment: prod
serviceName: hello-world-frontend

image:
  repository: gitops-hello-world-frontend
  tag: "0.0.1"

ingress:
  enabled: true
  hosts: 
  - host: hello-world.local
    paths:
    - path: /
      pathType: Prefix